---
title: "exposure_outcome_analysis"
author: "Melissa Tobin"
date: "31/05/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)

OS <- Sys.info()
if (OS["sysname"] == "Windows") {
  path <-
    "Z:/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
} else {
  path <-
    "/Volumes/hkr-storage/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
}
setwd(path)
```

## Loading Packages
```{r}
install.packages("lmtest")
library(lmtest)
library(tidyverse)
library(ggplot2)
library(haven)
library(janitor)
library(pastecs)
library(psych)
library(car)
library(Hmisc)
library(ggm)
library(polycor)
library(tableone)
library(forcats)
library(gmodels)
library(QuantPsyc)
library(KernSmooth)
library(raster)
library(sp)
library(sf)
```

## Reading in data
```{r}
gps_join_all_percent <- read_csv("gps_join_all_percent.csv")
wear_time_stamps <- read_csv("wear_time_stamps.csv")
#will need to read in GPS only if not already read in if other files are open
```

## Rename INTERACT ID to GPS ID
```{r}
colnames(gps_join_all_percent)[colnames(gps_join_all_percent)== "interact_id"] <- "gps_id" #this is the gps ID not interact ID. Changed name to reflect that
gps_join_all_percent[is.na(gps_join_all_percent <- gps_join_all_percent)] <- 0 #converted NA's to zero to make merging easier. 
```

## Merge gps_join_all_percent with victoria_gps_only 
```{r}
gps_join_all_percent[, "gps_id"] <- apply(gps_join_all_percent[, "gps_id"], 1, function(x) as.integer(x))
victoria_gps_only[, "gps_id"] <- apply(victoria_gps_only[, "gps_id"], 1, function(x) as.integer(x))
#converting to integar first so both gps_id are using the same data format

victoria_gps_only_merged <- left_join(victoria_gps_only, gps_join_all_percent, by = "gps_id") #successfully merged 
```

## Connect PA total and cycling PA with exposure data
```{r}
PA_total_and_cycling <- dplyr::select(victoria_gps_only_merged, "interact_id", "Cycling_formula", "total_pa_met_formula", "proportion_PA", "n.x", "n.y", "amount", "percent")

write_csv(PA_total_and_cycling, "PA_total_and_cycling.csv")
```

## Total hours, number of days and average hours 
```{r}
wear_time_stamps <- wear_time_stamps %>% group_by(interact_id) %>% mutate(total_hours = sum(unique_hours))

wear_time_stamps <- wear_time_stamps %>% group_by(interact_id) %>% mutate(number_days = sum(unique_days))

wear_time_stamps <- wear_time_stamps %>% group_by(interact_id) %>% mutate(average_hours = total_hours/number_days)

typeof(wear_time_stamps$interact_id)

summary_wear_stamps  <- dplyr::select(wear_time_stamps, "interact_id", "total_hours", "number_days", "average_hours") #creating a new data frame with just this info

summary_wear_stamps <- summary_wear_stamps %>% distinct(interact_id, .keep_all = TRUE) #removes duplicates
```

##Summary stats of wear time
```{r}
summary(summary_wear_stamps$total_hours)
summary(summary_wear_stamps$number_days)
summary(summary_wear_stamps$average_hours)

tabyl(summary_wear_stamps$total_hours)
```

