---
title: "gender_analysis"
author: "Melissa Tobin"
date: "26/06/2019"
output:   
  html_document:
        keep_md: true
---

```{r setup, include=FALSE}
chooseCRANmirror(graphics = FALSE, ind = 1)
knitr::opts_chunk$set(echo = TRUE)

OS <- Sys.info()
if (OS["sysname"] == "Windows") {
  path <-
    "Z:/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
} else {
  path <-
    "/Volumes/hkr-storage/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
}
setwd(path)

```

## Loading Packages
```{r}
library(lmtest)
library(tidyverse)
library(ggplot2)
library(haven)
library(janitor)
library(pastecs)
library(psych)
library(car)
library(Hmisc)
library(ggm)
library(polycor)
library(tableone)
library(forcats)
library(gmodels)
library(QuantPsyc)
library(KernSmooth)
library(raster)
library(sp)
library(sf)
library(data.table)
```

## Reading in Data
```{r}
power_victoria_merged_updated <- fread("power_victoria_merged_updated.csv") #big file with all summary counts - 151
victoria_new_ID_gps <- read_csv("victoria_new_ID_gps.csv") #all survey participant data - 281
victoria_small_merged_1 <- read_csv("victoria_small_merged_1.csv") #GPS participant survey data - 149

power_victoria_merged_filtered <- fread("power_victoria_merged_filtered.csv") #summary counts for 149 participants
summary_power_victoria_merged_filtered <- fread("summary_power_victoria_merged_filtered.csv")
```


```{r}
describeBy(victoria_new_ID_gps$age_calculated, victoria_new_ID_gps$gender)
```

## Plotting self-report PA by gender
```{r}
tabyl(victoria_new_ID_gps$gender)
 
PA_plot <- ggplot (data = victoria_new_ID_gps, aes(total_pa_met_formula)) + 
    geom_histogram(aes(fill = gender), position = "dodge", alpha = 0.5) + 
      labs(title = "Overall Physical Activity", 
          x = "Total MET Minutes of Physical Activity", 
          y = "Percent of Participants")
plot(PA_plot)

CrossTable(victoria_new_ID_gps$total_pa_met_formula, victoria_new_ID_gps$gender)

table(victoria_new_ID_gps$total_pa_met_formula, victoria_new_ID_gps$gender)

```

## Plotting activity count PA by gender

```{r}
power_victoria_merged_filtered <- fread("power_victoria_merged_filtered.csv")

activity_count_plot <- ggplot (data = power_victoria_merged_filtered, aes(summary_count)) + 
    geom_density(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Activity Count Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(activity_count_plot)
```

## Plotting summary PA by gender
```{r}
summary_power_victoria_merged_filtered <- fread("summary_power_victoria_merged_filtered.csv")

summary_activity_count_plot <- ggplot (data = summary_power_victoria_merged_filtered, aes(total_pa)) + 
    geom_density(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Summary Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(summary_activity_count_plot)
```

## Plotting Moderate PA by gender
```{r}
moderate_pa_plot <- ggplot (data = summary_power_victoria_merged_filtered, aes(total_moderate)) + 
    geom_density(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Summary Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(moderate_pa_plot)
```

## Plotting vigorous PA by gender
```{r}
vigorous_pa_plot <- ggplot (data = summary_power_victoria_merged_filtered, aes(total_vigorous)) + 
    geom_density(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Summary Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(vigorous_pa_plot)
```

## Plotting light PA by gender
```{r}
light_pa_plot <- ggplot (data = summary_power_victoria_merged_filtered, aes(total_light)) + 
    geom_histogram(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Summary Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(light_pa_plot)
```

## PLotting Sedentary PA by gender
```{r}
sedentary_pa_plot <- ggplot (data = summary_power_victoria_merged_filtered, aes(total_sedentary)) + 
    geom_histogram(aes(fill = gender_updated), position = "dodge", alpha = 0.5) + 
      labs(title = "Summary Accelerometer Physical Activity", 
          x = "Activity Count", 
          y = "Percent of Participants")
plot(sedentary_pa_plot)
```

## 
```{r}


gender_regression <- lm(total_pa_met_formula ~ gender_updated,  data = victoria_small_merged_1)

summary(gender_regression)

gender_regression_1 <- lm(Cycling_formula ~ gender_updated,  data = victoria_small_merged_1)

summary(gender_regression_1)
```

```{r}
gender_regression_2 <- lm(percent ~ gender_updated,  data = victoria_small_merged_1)
summary(gender_regression_2)
```

##AAA Support
```{r}
table(victoria_new_ID_gps$aaa_bike_more_1, victoria_new_ID_gps$gender)
tabyl(victoria_new_ID_gps$aaa_idea_1)

table(victoria_new_ID_gps$aaa_familiarity_1, victoria_new_ID_gps$gender)
table(victoria_new_ID_gps$aaa_idea_1, victoria_new_ID_gps$gender)

tabyl(victoria_new_ID_gps$bike_safety)
table(victoria_new_ID_gps$bike_safety, victoria_new_ID_gps$gender)

describeBy(victoria_new_ID_gps$bike_freq_a, victoria_new_ID_gps$gender)

describeBy(victoria_new_ID_gps$bike_freq_b, victoria_new_ID_gps$gender)

describeBy(victoria_new_ID_gps$bike_freq_c, victoria_new_ID_gps$gender)

describeBy(victoria_new_ID_gps$bike_freq_d, victoria_new_ID_gps$gender)
```

```{r}
bike_frequency_1 <- data.frame(season = c("fall", "fall", "fall", "winter", "winter", "winter", "spring", "spring",  "spring", "summer", "summer", "summer"), 
                           average_days = c(64.1, 56.5, 60.0, 52.6, 44.6, 48.2, 65.9, 59.6, 62.6, 71.8, 64.1, 67.9),
                           gender = c("men", "women", "total", "men", "women", "total", "men", "women", "total", "men", "women", "total"))

bike_frequency_plot <- ggplot(bike_frequency_1) +
  geom_point(aes(x = season, y = average_days, colour = gender, size = 1)) + 
  labs(title = "Average Number of Cycling Days per Season", 
          x = "Season", 
          y = "Average Number of Days") 
  
```

