---
title: "regression_models"
author: "Melissa Tobin"
date: "19/06/2019"
output:   
  html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
chooseCRANmirror(graphics = FALSE, ind = 1)

OS <- Sys.info()
if (OS["sysname"] == "Windows") {
  path <-
    "Z:/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
} else {
  path <-
    "/Volumes/hkr-storage/Research/dfuller/Walkabilly/people/Melissa Tobin/Thesis Results/INTERACT thesis Analysis"
}
setwd(path)
```

## Loading Packages
```{r}
library(lmtest)
library(tidyverse)
library(ggplot2)
library(haven)
library(janitor)
library(pastecs)
library(psych)
library(car)
library(Hmisc)
library(ggm)
library(polycor)
library(tableone)
library(forcats)
library(gmodels)
library(QuantPsyc)
library(KernSmooth)
library(raster)
library(sp)
library(sf)
library(lubridate)
library(anytime)
library(stringr)
library(stringi)
library(finalfit)
library(data.table)
install.packages("devtools")
devtools::install_github("cardiomoon/ggiraphExtra")
require(ggiraph)
require(ggiraphExtra)
require(plyr)
```

## Reading in data
```{r}
victoria_small_merged_1 <- fread("victoria_small_merged_1.csv")

power_victoria_merged <- fread("power_victoria_merged.csv") #big file with all summary counts
table_of_power_merged_2 <- fread("table_of_power_merged_2.csv")
summary_power_victoria_merged <- fread("summary_power_victoria_merged.csv") #summary table with summarized PA
```

## Variables
```{r}
power_victoria_merged$income_2 <- factor(power_victoria_merged$income_2, c("$49,000 or less", "$50,000 to $99,999", "$100,000 to $149,999", "$150,000 or more", "I don't know/Prefer not to answer")) 
```

## Models
```{r}
regression_1 <- lm(total_pa_met_formula ~ percent, data = victoria_small_merged_1)

summary(regression_1)
lm.beta(regression_1) ##This isn't working. 
confint(regression_1)
#plot(regression_1

ggPredict(regression_1, se = TRUE, interactive = TRUE)

ggplot(victoria_small_merged_1, aes(y = total_pa_met_formula, x = percent)) + 
  geom_point() +
  geom_smooth(method = "lm")
```


## Regression Model with Survey Data
```{r}
victoria_small_merged_1 <- victoria_small_merged_1 %>% 
                              mutate_at(vars(income_2, age_categories, ethnicity_updated), as.factor)

explanatory = c("percent", "gender_updated", "age_categories", "ethnicity_updated", "income_2", "mean_temp_date", "total_precip_date")
dependent = "total_pa_met_formula"
victoria_small_merged_1 %>% finalfit(dependent, explanatory) -> t1
knitr::kable(t1, row.names = FALSE, align = c("l", "l", "r", "r", "r")) 



lm_1 <- lm(total_pa_met_formula ~ percent + gender_updated + age_categories + ethnicity_updated + income_2 + mean_temp_date + total_precip_date, data = victoria_small_merged_1)
summary(lm_1)

victoria_small_merged_1$lm_fitted <- fitted(lm_1)

#ggplot(data = lm_1, aes(fitted, model$total_pa_met_formula)) + 
         #geom_point()

```

## Regression Model with summarry accelerometer data
```{r}
summary_power_victoria_merged <- summary_power_victoria_merged %>% 
                              mutate_at(vars(income_2, age_categories, ethnicity_updated), as.factor)
explanatory = c("percent", "gender_updated", "age_categories", "ethnicity_updated", "income_2", "mean_temp_date", "total_precip_date")
dependent = "total_pa"
summary_power_victoria_merged %>% finalfit(dependent, explanatory) -> t2
knitr::kable(t2, row.names = FALSE, align = c("l", "l", "r", "r", "r")) 
```

## Simple regression plot
```{r}
ggplot(summary_power_victoria_merged, aes(y = total_pa, x = percent)) + 
  geom_point() +
  geom_smooth(method = "lm")
```

## Regression Model with summary_counts as outcome variable - from accelerometer data
```{r}
power_victoria_merged <- power_victoria_merged %>% 
                              mutate_at(vars(income_2, age_categories, ethnicity_updated), as.factor)
explanatory = c("percent", "doy_1", "gender_updated", "age_categories", "ethnicity_updated", "income_2", "mean_temp_date", "total_precip_date")
dependent = "summary_count"
power_victoria_merged %>% finalfit(dependent, explanatory) -> t3
knitr::kable(t3, row.names = FALSE, align = c("l", "l", "r", "r", "r")) 
```

ng on making plots for regression
```{r}
pa_regression_1 <- lm(summary_count ~ percent,  data = power_victoria_merged)

summary(pa_regression_1)
lm.beta(pa_regression_1) ##This isn't working. 
confint(pa_regression_1)

ggplot(power_victoria_merged, aes(y = summary_count, x = percent)) + 
  geom_point() +
  geom_smooth(method = "lm")
```

