---
title: "sensedoc_dates"
author: "Melissa Tobin"
date: "10/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rename INTERACT ID to GPS ID on the wear_time_stamps file
```{r}
colnames(wear_time_stamps)[colnames(wear_time_stamps)== "interact_id"] <- "gps_id" #this is the gps ID not interact ID. Changed name to reflect that
```

## Merge wear_time_stamps with victoria_gps_only 
```{r}
id_only <- dplyr::select(victoria_gps_only_merged, "interact_id", "gps_id", "sensedoc_ID" )

wear_time_stamps_ID <- left_join(wear_time_stamps, id_only, by = "gps_id")
```

## Merging sd_days with ID's 
```{r}
colnames(sd_days)[colnames(sd_days) == "Dates Worn"] <- "dates_worn"
colnames(sd_days)[colnames(sd_days) == "Serial #"] <- "serial"
colnames(sd_days)[colnames(sd_days) == "Sensedoc ID"] <- "sensedoc_ID"

sd_days_merged <- left_join(sd_days, id_only, by = "sensedoc_ID")
```

## Total hours, number of days and average hours 
```{r}
wear_time_stamps_ID <- wear_time_stamps_ID %>% group_by(interact_id) %>% mutate(total_hours = sum(unique_hours))

wear_time_stamps_ID <- wear_time_stamps_ID %>% group_by(interact_id) %>% mutate(number_days = sum(unique_days))

wear_time_stamps_ID <- wear_time_stamps_ID %>% group_by(interact_id) %>% mutate(average_hours = total_hours/number_days)

typeof(wear_time_stamps_ID$interact_id)

summary_wear_stamps  <- dplyr::select(wear_time_stamps_ID, "interact_id", "total_hours", "number_days", "average_hours") #creating a new data frame with just this info

summary_wear_stamps <- summary_wear_stamps %>% distinct(interact_id, .keep_all = TRUE) #removes duplicates
```

##Summary stats of wear time
```{r}
summary(summary_wear_stamps$total_hours)
summary(summary_wear_stamps$number_days)
summary(summary_wear_stamps$average_hours)

tabyl(summary_wear_stamps$total_hours)
```

## Wear time plots 
```{r}
histo_gps_points <- ggplot(wear_time_stamps) + 
                      geom_histogram(aes(unique_seconds)) + 
                      geom_vline(xintercept=7500)
plot(histo_gps_points)

```

## New time stamps 

```{r}
wear_time_stamps_updated <- read_csv("wear_time_stamps_updated.csv")
histo_gps_points_updated <- ggplot(wear_time_stamps_updated) + 
                      geom_histogram(aes(unique_seconds)) + 
                      geom_vline(xintercept=7500)
plot(histo_gps_points_updated)
```

## Dealing with SD timestampes
```{r}
sd_days_merged <- separate(sd_days_merged, dates_worn, c("start", "end"), sep = "-")

sd_days_merged <- sd_days_merged %>% dplyr::mutate(year = "2017") 
                             
sd_days_merged$start_recode <- stri_join(sd_days_merged$start, sd_days_merged$year, sep = " ", collapse = NULL, ignore_null = FALSE)

sd_days_merged$end_recode <- stri_join(sd_days_merged$end, sd_days_merged$year, sep = " ", collapse = NULL, ignore_null = FALSE)

sd_days_merged_1 <- read_csv("sd_days_merged_fixed.csv")

sd_days_merged_1$start_year <- mdy(sd_days_merged_1$start_recode)

sd_days_merged_1$end_year <- mdy(sd_days_merged_1$end_recode)


sd_days_merged_1 <- sd_days_merged_1 %>% mutate(doy_start = yday(start_year))

sd_days_merged_1 <- sd_days_merged_1 %>% mutate(doy_end = yday(end_year))

sd_days_merged_2 <- filter(sd_days_merged_1, interact_id > 1)

sd_doy <- dplyr::select(sd_days_merged_1, "sensedoc_ID", "interact_id", "doy_start", "doy_end")

wear_time_stamps_merged <- left_join(wear_time_stamps_ID, sd_doy, by = "sensedoc_ID")
```

## Filter for correct days of participants 
```{r}
filtered_time_stamps <- wear_time_stamps_merged %>% group_by(interact_id.x)  %>% filter(doy >= doy_start) %>% filter(doy <= doy_end) %>% filter(unique_seconds > 7500)

write_csv(filtered_time_stamps, "filtered_time_stamps.csv")
```

```{r}
filtered_time_stamps <- read_csv("filtered_time_stamps.csv")

colnames(filtered_time_stamps)[colnames(filtered_time_stamps)== "interact_id.x"] <- "interact_id"

doy_start_end <- dplyr::select(filtered_time_stamps, "interact_id", "gps_id", "doy", "doy_start", "doy_end", "unique_seconds")

doy_start_end_filtered <- dplyr::select(doy_start_end, "interact_id", "gps_id", "doy_start", "doy_end", "unique_seconds")

doy_start_end_filtered <- doy_start_end %>% distinct(interact_id, .keep_all = TRUE) #removes duplicates

write_csv(doy_start_end_filtered, "doy_start_end_filtered.csv")

doy_start_end_filtered <- read_csv("doy_start_end_filtered.csv")
```


```{r}
wear_time_stamps_updated_1 <- wear_time_stamps_updated %>% filter(unique_seconds > 7500)
```
